# Copyright (c) The nextest Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

# The rules are loaded from the .bzl files in this directory; this file exists
# so that the directory is a package.
